name: GHOST

on:
  push:
    branches:
      - main
  workflow_dispatch: # هذا يضيف زر "Run workflow" في واجهة GitHub
  
jobs:
  register_getscreen:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # استخدام أحدث إصدار
    
    - name: Install Tailscale
      run: |
          Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
          Start-Process .\tailscale-setup.exe -ArgumentList "/S" -Wait

    - name: Authenticate to Tailscale
      run: |
          &"C:\Program Files\Tailscale\tailscale.exe" up --auth-key tskey-auth-k1sAo8vpFN11CNTRL-aMFS56zy6VRqXz9xu8q7VRcPP1HGZycf # إدراج المفتاح مباشرة (ليس موصى به للأمان)
      
    - name: Change Password for runneradmin
      run: |
        net user runneradmin P@ssw0rd!
      shell: powershell
      continue-on-error: true # يتجاهل الخطأ في حالة عدم وجود صلاحيات كافية لتغيير كلمة المرور
   
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python Script
      run: python count_to_infinity.py
